options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _MCP_SERVER_URL: "http://127.0.0.1:8081/mcp"
  _VERTEX_AI_LOCATION: "us-central1"
  _VERTEX_AI_MODEL: "gemini-2.5-flash"
  _GEMINI_API_KEY: ""
  _VERTEX_API_KEY: ""
  _GOOGLE_MAPS_API_KEY: ""
  _RUNTIME_SERVICE_ACCOUNT: "mcp-toolbox-sa@gptrix.iam.gserviceaccount.com"

steps:
  # Step 1: Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/dynotrip-backend',
        '-f', 'backend/Dockerfile.all',
        'backend'
      ]

  # Step 2: Push the image to Container Registry (or Artifact Registry)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dynotrip-backend']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'dynotrip-backend',
        '--image', 'gcr.io/$PROJECT_ID/dynotrip-backend',
        '--region', 'us-central1',     # change this to your region
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/dynotrip-backend'
