steps:
  # Build MCP Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_MCP_SERVICE}:$COMMIT_SHA', '-f', 'backend/Dockerfile.mcp', '.']
    id: 'build-mcp'

  # Push MCP Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_MCP_SERVICE}:$COMMIT_SHA']

  # Deploy MCP Service
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_MCP_SERVICE}',
      '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_MCP_SERVICE}:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--platform', 'managed',
      '--port', '8080',
      '--set-secrets', 'GOOGLE_MAPS_API_KEY=GOOGLE_MAPS_API_KEY:latest',
      '--update-secrets', '/secrets/gcp-credentials.json=GOOGLE_APPLICATION_CREDENTIALS:latest',
      '--update-env-vars', 'GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-credentials.json'
    ]

  # Get MCP Service URL
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'get-mcp-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        MCP_URL=$(gcloud run services describe ${_MCP_SERVICE} --region ${_REGION} --format 'value(status.url)')
        echo "MCP Service URL: $MCP_URL"
        echo "MCP_SERVER_URL=$MCP_URL" >> /workspace/.env

  # Build API Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_SERVICE}:$COMMIT_SHA', '-f', 'backend/Dockerfile.api', '--build-arg', 'GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-credentials.json', '.']
    id: 'build-api'

  # Push API Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_SERVICE}:$COMMIT_SHA']

  # Deploy API Service
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', '${_API_SERVICE}',
      '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_API_SERVICE}:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--platform', 'managed',
      '--port', '8080',
      '--set-secrets', 'GEMINI_API_KEY=GEMINI_API_KEY:latest,VERTEX_API_KEY=VERTEX_API_KEY:latest,PROJECT_ID=PROJECT_ID:latest,VERTEX_AI_MODEL=VERTEX_AI_MODEL:latest',
      '--update-secrets', '/secrets/gcp-credentials.json=GOOGLE_APPLICATION_CREDENTIALS:latest',
      '--update-env-vars', 'MCP_SERVER_URL=$MCP_URL,VERTEX_AI_LOCATION=${_REGION},GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-credentials.json'
    ]

options:
  logging: CLOUD_LOGGING_ONLY