options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build unified backend image from Dockerfile.all
  - name: gcr.io/cloud-builders/docker
    id: build-backend
    args:
      - build
      - -t
      - "us-central1-docker.pkg.dev/$PROJECT_ID/dynotrip-repo/dynotrip-backend:$COMMIT_SHA"
      - -f
      - backend/Dockerfile.all
      - .

  # Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: push-backend
    args:
      - push
      - "us-central1-docker.pkg.dev/$PROJECT_ID/dynotrip-repo/dynotrip-backend:$COMMIT_SHA"

  # Deploy single Cloud Run service (API on 8080; MCP runs inside on 8081)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-backend
    entrypoint: gcloud
    args:
      - run
      - deploy
      - dynotrip-backend
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/dynotrip-repo/dynotrip-backend:$COMMIT_SHA
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --set-env-vars=MCP_SERVER_URL=http://127.0.0.1:8081,VERTEX_AI_LOCATION=us-central1
      - --set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest,VERTEX_API_KEY=VERTEX_API_KEY:latest,PROJECT_ID=PROJECT_ID:latest,VERTEX_AI_MODEL=VERTEX_AI_MODEL:latest,GOOGLE_MAPS_API_KEY=GOOGLE_MAPS_API_KEY:latest
      - --update-secrets=/secrets/gcp-credentials.json=GOOGLE_APPLICATION_CREDENTIALS:latest
      - --update-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/secrets/gcp-credentials.json

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/dynotrip-repo/dynotrip-backend:$COMMIT_SHA
