options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _MCP_SERVER_URL: "http://127.0.0.1:8081/mcp"
  _VERTEX_AI_LOCATION: "us-central1"
  _VERTEX_AI_MODEL: "gemini-2.5-flash"
  _GEMINI_API_KEY: ""
  _VERTEX_API_KEY: ""
  _GOOGLE_MAPS_API_KEY: ""
  _RUNTIME_SERVICE_ACCOUNT: "mcp-toolbox-sa@gptrix.iam.gserviceaccount.com"

steps:
  # Build image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'us-central1-docker.pkg.dev/gptrix/dynotrip-repo/backend',
        '-f', 'Dockerfile.all',
        '.'
      ]

  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gptrix/dynotrip-repo/backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'dynotrip-backend',
        '--image', 'us-central1-docker.pkg.dev/gptrix/dynotrip-repo/backend',
        '--region', 'us-central1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--timeout', '900'
      ]

images:
  - 'us-central1-docker.pkg.dev/gptrix/dynotrip-repo/backend'

